baseURL = 'https://ksgab2.github.io/'
title = '교육 블로그'
theme = 'hugo-theme-cleanwhite'
languageCode = 'ko-kr'
hasCJKLanguage = true

[params]
  title = "Book Bot Library"
  subtitle = "Node.js 자동화 봇이 5분마다 수집하는 실시간 도서 정보"
  location = "Seoul, South Korea"
  header_image = "img/home-bg.jpg"
  sidebar = true
  sidebar_avatar = "img/avatar.png"
  bio = "AI교육 블로그입니다."
  featured_tags = true
  featured_fast = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

# Clean White 테마가 내 글 폴더(post)를 메인 화면에 불러오도록 강제 지정
[permalinks]
  post = "/:year/:month/:day/:slug/"

[frontmatter]
  staticDir = ["static"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true